### ISSUE TITLE
Clone Repo into your machine

### ISSUE THREAD

**Issue by mj434** [mj434/P1_218#1]

**Comment by mj434** [comment]
![image](https://user-images.githubusercontent.com/70653516/135330115-a65a042c-e00e-4ed6-82f0-3ea8c363db50.png)

**Comment by OmarElserty96** [comment]
![image](https://user-images.githubusercontent.com/91627675/135330596-58e8a3f6-0ab1-448b-a768-c1afac628fba.png)
